"""test change

Revision ID: 53c2ae2df15d
Revises: 1cfb48928f42
Create Date: 2013-06-19 23:35:52.802639

"""

# revision identifiers, used by Alembic.
revision = '53c2ae2df15d'
down_revision = '1cfb48928f42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'test')
    op.drop_column('secrets', u'dummy_column')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column(u'dummy_column', sa.VARCHAR(), nullable=True))

    op.create_table(
        'test',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('description', sa.Unicode(200)),
    )

    # op.create_table(u'test',
    # sa.Column(u'id', sa.INTEGER(), server_default="nextval('test_id_seq'::regclass)", nullable=False),
    # sa.Column(u'name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column(u'description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint(u'id', name=u'test_pkey')
    # )
    ### end Alembic commands ###
